// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RustAdminPanel.DAL.Context;

#nullable disable

namespace RustAdminPanel.DAL.Migrations
{
    [DbContext(typeof(RustAdminPanelContext))]
    partial class RustAdminPanelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("RustAdminPanel.Domain.Entities.PlayerConnectionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ConnectionTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlayerConnectionLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
